services:
  - type: worker
    name: tiktok-otp-blaster-bot
    env: python
    pythonVersion: "3.12.0"
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    plan: standard
    autoDeploy: true
